project_id = "lnknravwmxqdymefwiax"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation_enabled = true

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[functions.youtube-verification]
verify_jwt = true

[functions.campaign-management]
verify_jwt = true

[functions.gamification-system]
verify_jwt = true

[functions.referral-system]
verify_jwt = true

[functions.moderation]
verify_jwt = true

[functions.push-notifications]
verify_jwt = true

[functions.fraud-detection]
verify_jwt = true

[edge_runtime]
policy = "per_worker"
inspector_port = 8083