// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnknravwmxqdymefwiax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxua25yYXZ3bXhxZHltZWZ3aWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTYzNTQsImV4cCI6MjA3NDE5MjM1NH0.pvvNINvm_HxH4psugvjP9EKtMFqDG1aWF8yoqrTHeLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});